# Dev overrides. The tag below is rewritten by CI (update-dev-tag job) after
# every successful image push from the develop branch.
image:
  tag: sha-bea8df875ba7a378f7a06ad6e1049e9104dc7d8f
  pullPolicy: IfNotPresent
