apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: onsen-scrawler-dev
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/steveTheCyberDev/onsen_scrawler.git
    targetRevision: develop
    path: charts/onsen-scrawler
    helm:
      releaseName: onsen-scrawler
      valueFiles:
        - values-dev.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: onsen-dev   # dev is a namespace in the same cluster
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
